*Francisco Pereira [camara@dtu.dk], DTU Management*



# Advanced Business Analytics

## Lecture 1 - Web Data Mining - Part 4: European Environmental Agency data

In this notebook, we explore the EEA's dataset API. In their system, they assume that each call is essentially an SQL query. This implies that we need to know well the databases that they have. 

Therefore, the first thing to do, is take a look at their database structure

https://discodata.eea.europa.eu/#

#### 1.1. A simple example

First, the imports...

In [1]:
import requests
import json
import matplotlib.pyplot as plt
import pandas as pd

/var/folders/vk/wc7mk0p13r31xnm_nqv76gnh0000gp/T/ipykernel_11735/2183480416.py:4: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

We will not be able to teach you about SQL. For what you need for this, the amount of SQL required is actually pretty basic (just google for the sintax of the SQL select command).

Here is an example, where we want to get the table "metada" that is in the V2 version of the "metadata" database:

In [2]:
http="https://discodata.eea.europa.eu/sql?query=Select * from [metadata].[v2].[metadata]"
res = requests.get(http)

In [3]:
len(res.content)

26123607

This is actually a LOT of data, so unless you are really patient (and have a good computer), we recommend you to pick specific fields. Here's an example

In [4]:
jsonres=json.loads(res.content)

In [5]:
eea_m_df=pd.DataFrame(jsonres['results'])

In [6]:
eea_m_df

,identifier,parentIdentifier,objectType,title,description,creatorElectronicMailAddress,creatorOrganisationName,created,language,license,rights,rightsHolder,statusCode,statusDate,statusRemarks,SQLRestApi
0,[AirQualityDataFlows],None,catalog,None,None,info@eea.europa.eu,European Environment Agency,None,eng,https://creativecommons.org/licenses/by/4.0/,None,None,submitted,2024-02-03,None,1
1,[AirQualityDataFlows].[latest],[AirQualityDataFlows],schema,None,The lastest version and revision for every sin...,info@eea.europa.eu,European Environment Agency,None,eng,https://creativecommons.org/licenses/by/4.0/,None,None,submitted,2024-02-03,None,1
2,[AirQualityDataFlows].[latest].[AirQualityStat...,[AirQualityDataFlows].[latest],view,None,None,info@eea.europa.eu,European Environment Agency,None,eng,https://creativecommons.org/licenses/by/4.0/,None,None,submitted,2024-02-03,None,1
3,[AirQualityDataFlows].[latest].[AirQualityStat...,[AirQualityDataFlows].[latest].[AirQualityStat...,column,None,Flag filtering data accepted for products in Q...,info@eea.europa.eu,European Environment Agency,None,eng,https://creativecommons.org/licenses/by/4.0/,None,None,submitted,2024-02-03,None,1
4,[AirQualityDataFlows].[latest].[AirQualityStat...,[AirQualityDataFlows].[latest].[AirQualityStat...,column,None,"Air polluting substance, level of which is mea...",info@eea.europa.eu,European Environment Agency,None,eng,https://creativecommons.org/licenses/by/4.0/,None,None,submitted,2024-02-03,None,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45341,[WISE_WFD].[v1r1].[SWMET_SWType].[swTypeDescri...,[WISE_WFD].[v1r1].[SWMET_SWType],column,swTypeDescription,Required. Briefly describe the type (e.g. smal...,info@eea.europa.eu,European Environment Agency,None,eng,https://creativecommons.org/licenses/by/4.0/,None,None,submitted,2024-02-03,None,1
45342,[WISE_WFD].[v1r1].[SWMET_SWType].[swTypeSpecif...,[WISE_WFD].[v1r1].[SWMET_SWType],column,swTypeSpecificReferenceConditionsForBQEs,Required. Indicate whether type-specific refer...,info@eea.europa.eu,European Environment Agency,None,eng,https://creativecommons.org/licenses/by/4.0/,None,None,submitted,2024-02-03,None,1
45343,[WISE_WFD].[v1r1].[SWMET_SWType].[swTypeSpecif...,[WISE_WFD].[v1r1].[SWMET_SWType],column,swTypeSpecificReferenceConditionsForHyMoQEs,Required. Indicate whether type-specific refer...,info@eea.europa.eu,European Environment Agency,None,eng,https://creativecommons.org/licenses/by/4.0/,None,None,submitted,2024-02-03,None,1
45344,[WISE_WFD].[v1r1].[SWMET_SWType].[swTypeSpecif...,[WISE_WFD].[v1r1].[SWMET_SWType],column,swTypeSpecificReferenceConditionsForPhysChemQEs,Required. Indicate whether type-specific refer...,info@eea.europa.eu,European Environment Agency,None,eng,https://creativecommons.org/licenses/by/4.0/,None,None,submitted,2024-02-03,None,1
45345,[WISE_WFD].[v1r1].[SWMET_SWType].[wiseEvolutio...,[WISE_WFD].[v1r1].[SWMET_SWType],column,wiseEvolutionType,--Definition-- \r\nType of event that produced...,info@eea.europa.eu,European Environment Agency,None,eng,https://creativecommons.org/licenses/by/4.0/,None,None,submitted,2024-02-03,None,1

Well, yes, this one is still confusing. Feel free to explore another database.

#### 1.2. Biodiversity data

EEA data has many different things, so we're now going for something of our choice: EUNIS, the European Nature Information System

Take a look at https://eunis.eea.europa.eu


We will start with a table with generic statistics about the different countries. Just take a look

In [7]:
url="https://discodata.eea.europa.eu/sql?query=Select * from [EUNIS].[v1r3].[Art12_mastertab_data_detail]"

In [8]:
res = requests.get(url)

In [9]:
jsonres=json.loads(res.content)

In [10]:
jsonres

{'results': [{'country': 'AT',
   'season': 'B',
   'speciescode': 'A004',
   'speciesname': 'Tachybaptus ruficollis',
   'sub_unit': None,
   'alternative_speciesname': None,
   'common_speciesname': 'Zwergtaucher',
   'population_date': '2013-2018',
   'population_size_unit': 'p',
   'population_size_min': 900,
   'population_size_max': 1200,
   'population_size': None,
   'population_estimate_type': 'estimate',
   'population_method': 'completeSurvey',
   'population_sources': 'BirdLife Austria, unpublished data from www.ornitho.at',
   'population_info': None,
   'population_trend_period': '2007-2018',
   'population_trend': 'I',
   'population_trend_magnitude_min': 15,
   'population_trend_magnitude_max': 30,
   'population_trend_magnitude': None,
   'population_trend_method': 'estimatePartial',
   'population_trend_sources': 'BirdLife Austria, unpublished data from www.ornitho.at; BirdLife Austria, unpublished archive data',
   'population_trend_long_period': '1981-2018',
   'population_trend_long': 'D',
   'population_trend_long_magnitude_min': -20,
   'population_trend_long_magnitude_max': -10,
   'population_trend_long_magnitude': None,
   'population_trend_long_method': 'completeSurvey',
   'population_trend_long_sources': 'Dvorak et al. 1994',
   'population_trend_info': None,
   'sensitive_species': False,
   'distribution_period': '2013-2018',
   'distribution_map': True,
   'distribution_grid_area': '19900',
   'distribution_surface_area': 21200,
   'distribution_method': 'completeSurvey',
   'additional_distribution_map': False,
   'distribution_source': 'BirdLife Austria, unpublished data from www.ornitho.at',
   'distribution_info': None,
   'distribution_trend_period': '2007-2018',
   'distribution_trend': 'D',
   'distribution_trend_magnitude_min': None,
   'distribution_trend_magnitude_max': None,
   'distribution_trend_magnitude': -21,
   'distribution_trend_method': 'completeSurvey',
   'distribution_trend_source': 'BirdLife Austria, unpublished data from www.ornitho.at; BirdLife Austria, unpublished archive data',
   'distribution_trend_long_period': '1981-2018',
   'distribution_trend_long': 'I',
   'distribution_trend_long_magnitude_min': 15,
   'distribution_trend_long_magnitude_max': 30,
   'distribution_trend_long_magnitude': None,
   'distribution_trend_long_method': 'completeSurvey',
   'distribution_trend_long_source': 'Dvorak, Ranner & Berg 1993 (Atlas of Austrian Breeding Birds)',
   'distribution_trend_info': None,
   'plan': 'NA',
   'national_plan_adopted': False,
   'measures_taken': None,
   'effectiveness_SAPs': None,
   'effectiveness_MPs': None,
   'further_info': None,
   'spa_population_unit': None,
   'spa_population_min': None,
   'spa_population_max': None,
   'spa_population': None,
   'spa_population_estimate_type': None,
   'spa_population_method': None,
   'spa_population_trend': None,
   'spa_population_trend_method': None,
   'spa_info': None,
   'use_for_statistics': True,
   'popsize_etc': 1050.0,
   'spa_popsize_etc': None,
   'spa_coverage_etc': None},
  {'country': 'AT',
   'season': 'B',
   'speciescode': 'A005',
   'speciesname': 'Podiceps cristatus',
   'sub_unit': None,
   'alternative_speciesname': None,
   'common_speciesname': 'Haubentaucher',
   'population_date': '2013-2018',
   'population_size_unit': 'p',
   'population_size_min': 1000,
   'population_size_max': 1700,
   'population_size': None,
   'population_estimate_type': 'estimate',
   'population_method': 'completeSurvey',
   'population_sources': 'BirdLife Austria, unpublished data from www.ornitho.at',
   'population_info': None,
   'population_trend_period': '2007-2018',
   'population_trend': 'U',
   'population_trend_magnitude_min': 20,
   'population_trend_magnitude_max': 50,
   'population_trend_magnitude': None,
   'population_trend_method': 'estimateExpert',
   'population_trend_sources': 'BirdLife Austria, unpublished data from www.ornitho.at; BirdLife Austria, unpublished archive data',
   'population_trend_long_period': '1981-2018',
   'population_trend_long': 'I',
   'population_trend_long_magnitude_min': 20,
   'population_trend_long_magnitude_max': 40,
   'population_trend_long_magnitude': None,
   'population_trend_long_method': 'completeSurvey',
   'population_trend_long_sources': 'Dvorak et al. 1994; representativness of short term trend uncertain because no recent data on  population sizes  for several important breeding populations on large lakes (e.g. Wörther See, Ossiacher See) and in fish pond areas (e.g. Waldviertel)',
   'population_trend_info': None,
   'sensitive_species': False,
   'distribution_period': '2013-2018',
   'distribution_map': True,
   'distribution_grid_area': '14300',
   'distribution_surface_area': 15100,
   'distribution_method': 'completeSurvey',
   'additional_distribution_map': False,
   'distribution_source': 'BirdLife Austria, unpublished data from www.ornitho.at',
   'distribution_info': None,
   'distribution_trend_period': '2007-2018',
   'distribution_trend': 'D',
   'distribution_trend_magnitude_min': None,
   'distribution_trend_magnitude_max': None,
   'distribution_trend_magnitude': -33,
   'distribution_trend_method': 'completeSurvey',
   'distribution_trend_source': 'BirdLife Austria, unpublished data from www.ornitho.at; BirdLife Austria, unpublished archive data',
   'distribution_trend_long_period': '1981-2018',
   'distribution_trend_long': 'I',
   'distribution_trend_long_magnitude_min': 15,
   'distribution_trend_long_magnitude_max': 30,
   'distribution_trend_long_magnitude': None,
   'distribution_trend_long_method': 'completeSurvey',
   'distribution_trend_long_source': 'Dvorak, Ranner & Berg 1993 (Atlas of Austrian Breeding Birds)',
   'distribution_trend_info': None,
   'plan': 'NA',
   'national_plan_adopted': False,
   'measures_taken': None,
   'effectiveness_SAPs': None,
   'effectiveness_MPs': None,
   'further_info': None,
   'spa_population_unit': None,
   'spa_population_min': None,
   'spa_population_max': None,
   'spa_population': None,
   'spa_population_estimate_type': None,
   'spa_population_method': None,
   'spa_population_trend': None,
   'spa_population_trend_method': None,
   'spa_info': None,
   'use_for_statistics': True,
   'popsize_etc': 1350.0,
   'spa_popsize_etc': None,
   'spa_coverage_etc': None},
  {'country': 'AT',
   'season': 'B',
   'speciescode': 'A008',
   'speciesname': 'Podiceps nigricollis',
   'sub_unit': None,
   'alternative_speciesname': None,
   'common_speciesname': 'Schwarzhalstaucher',
   'population_date': '2013-2017',
   'population_size_unit': 'p',
   'population_size_min': 0,
   'population_size_max': 21,
   'population_size': None,
   'population_estimate_type': 'estimate',
   'population_method': 'completeSurvey',
   'population_sources': 'BirdLife Austria, unpublished data from the bird monitoring programm of the Neusiedler See - Seewinkel national park',
   'population_info': None,
   'population_trend_period': '2007-2018',
   'population_trend': 'I',
   'population_trend_magnitude_min': None,
   'population_trend_magnitude_max': None,
   'population_trend_magnitude': 178,
   'population_trend_method': 'completeSurvey',
   'population_trend_sources': 'BirdLife Austria, unpublished data from the bird monitoring programm of the Neusiedler See - Seewinkel national park',
   'population_trend_long_period': '1981-2018',
   'population_trend_long': 'D',
   'population_trend_long_magnitude_min': None,
   'population_trend_long_magnitude_max': None,
   'population_trend_long_magnitude': -97,
   'population_trend_long_method': 'estimatePartial',
   'population_trend_long_sources': 'Dvorak et al. 1994, Dvorak et al. 2016, unpublished data from various sources and databases',
   'population_trend_info': None,
   'sensitive_species': False,
   'distribution_period': '2013-2018',
   'distribution_map': True,
   'distribution_grid_area': '300',
   'distribution_surface_area': 300,
   'distribution_method': 'completeSurvey',
   'additional_distribution_map': False,
   'distribution_source': 'BirdLife Austria, unpublished data from www.ornitho.at',
   'distribution_info': None,
   'distribution_trend_period': '2007-2018',
   'distribution_trend': 'S',
   'distribution_trend_magnitude_min': None,
   'distribution_trend_magnitude_max': None,
   'distribution_trend_magnitude': 0,
   'distribution_trend_method': 'completeSurvey',
   'distribution_trend_source': 'BirdLife Austria, unpublished data from www.ornitho.at; BirdLife Austria, unpublished archive data',
   'distribution_trend_long_period': '1981-2018',
   'distribution_trend_long': 'D',
   'distribution_trend_long_magnitude_min': None,
   'distribution_trend_long_magnitude_max': None,
   'distribution_trend_long_magnitude': -90,
   'distribution_trend_long_method': 'completeSurvey',
   'distribution_trend_long_source': 'BirdLife Austria, unpublished data from www.ornitho.at, Dvorak, Ranner & Berg  1993 (Atlas of Austrian breeding birds 1981-1985)',
   'distribution_trend_info': None,
   'plan': 'NA',
   'national_plan_adopted': False,
   'measures_taken': None,
   'effectiveness_SAPs': None,
   'effectiveness_MPs': None,
   'further_info': None,
   'spa_population_unit': 'p',
   'spa_population_min': 0,
   'spa_population_max': 21,
   'spa_population': None,
   'spa_population_estimate_type': 'estimate',
   'spa_population_method': 'completeSurvey',
   'spa_population_trend': 'D',
   'spa_population_trend_method': 'completeSurvey',
   'spa_info': None,
   'use_for_statistics': True,
   'popsize_etc': 10.5,
   'spa_popsize_etc': 10.5,
   'spa_coverage_etc': 100.0},
  {'country': 'AT',
   'season': 'B',
   'speciescode': 'A021',
   'speciesname': 'Botaurus stellaris',
   'sub_unit': None,
   'alternative_speciesname': None,
   'common_speciesname': 'Rohrdommel',
   'population_date': '2013-2018',
   'population_size_unit': 'cmales',
   'population_size_min': 110,
   'population_size_max': 170,
   'population_size': None,
   'population_estimate_type': 'estimate',
   'population_method': 'estimatePartial',
   'population_sources': 'Dvorak et al. 2016; Michael Dvorak & Erwin Nemeth, unpublished data from the bird monitoring program of the national park Neusiedler See-Seewinkel; BirdLife Austria, unpublished data from www.ornitho.at',
   'population_info': '100-150 Neusiedler See, 10-20 Seewinkel',
   'population_trend_period': '2007-2013',
   'population_trend': 'D',
   'population_trend_magnitude_min': -60,
   'population_trend_magnitude_max': -40,
   'population_trend_magnitude': None,
   'population_trend_method': 'completeSurvey',
   'population_trend_sources': 'Dvorak et al. 2016; Michael Dvorak & Erwin Nemeth, unpublished data from the bird monitoring program of the national park Neusiedler See-Seewinkel',
   'population_trend_long_period': '1981-2018',
   'population_trend_long': 'Unk',
   'population_trend_long_magnitude_min': None,
   'population_trend_long_magnitude_max': None,
   'population_trend_long_magnitude': None,
   'population_trend_long_method': 'absentData',
   'population_trend_long_sources': 'Dvorak et al. 2016; Michael Dvorak & Erwin Nemeth, unpublished data from the bird monitoring program of the national park Neusiedler See-Seewinkel; Dvorak, Ranner & Berg 1993 (Atlas of Austrian Breeding Birds)',
   'population_trend_info': None,
   'sensitive_species': False,
   'distribution_period': '2013-2018',
   'distribution_map': True,
   'distribution_grid_area': '1000',
   'distribution_surface_area': 1200,
   'distribution_method': 'completeSurvey',
   'additional_distribution_map': False,
   'distribution_source': 'BirdLife Austria, unpublished data from www.ornitho.at',
   'distribution_info': None,
   'distribution_trend_period': '2007-2018',
   'distribution_trend': 'S',
   'distribution_trend_magnitude_min': None,
   'distribution_trend_magnitude_max': None,
   'distribution_trend_magnitude': 0,
   'distribution_trend_method': 'completeSurvey',
   'distribution_trend_source': 'BirdLife Austria, unpublished data from www.ornitho.at; BirdLife Austria, unpublished archive data from www.ornitho.at',
   'distribution_trend_long_period': '1981-2018',
   'distribution_trend_long': 'I',
   'distribution_trend_long_magnitude_min': 15,
   'distribution_trend_long_magnitude_max': 30,
   'distribution_trend_long_magnitude': None,
   'distribution_trend_long_method': 'completeSurvey',
   'distribution_trend_long_source': 'BirdLife Austria, unpublished data from www.ornitho.at; Dvorak, Ranner & Berg 1993 (Atlas of Austrian Breeding Birds)',
   'distribution_trend_info': None,
   'plan': 'SAP',
   'national_plan_adopted': False,
   'measures_taken': 'no measures taken',
   'effectiveness_SAPs': 'unchanged',
   'effectiveness_MPs': None,
   'further_info': 'no further information',
   'spa_population_unit': 'cmales',
   'spa_population_min': 110,
   'spa_population_max': 170,
   'spa_population': None,
   'spa_population_estimate_type': 'estimate',
   'spa_population_method': 'completeSurvey',
   'spa_population_trend': 'D',
   'spa_population_trend_method': 'completeSurvey',
   'spa_info': None,
   'use_for_statistics': True,
   'popsize_etc': 140.0,
   'spa_popsize_etc': 140.0,
   'spa_coverage_etc': 100.0},
  {'country': 'AT',
   'season': 'B',
   'speciescode': 'A022',
   'speciesname': 'Ixobrychus minutus',
   'sub_unit': None,
   'alternative_speciesname': None,
   'common_speciesname': 'Zwergdommel',
   'population_date': '2013-2018',
   'population_size_unit': 'p',
   'population_size_min': 400,
   'population_size_max': 600,
   'population_size': None,
   'population_estimate_type': 'estimate',
   'population_method': 'completeSurvey',
   'population_sources': 'BirdLife Austria, unpublished data from www.ornitho.at',
   'population_info': None,
   'population_trend_period': '2007-2018',
   'population_trend': 'I',
   'population_trend_magnitude_min': 80,
   'population_trend_magnitude_max': 120,
   'population_trend_magnitude': None,
   'population_trend_method': 'estimatePartial',
   'population_trend_sources': 'BirdLife Austria, unpublished data from www.ornitho.at; BirdLife Austria, unpublished archive data',
   'population_trend_long_period': '1981-2018',
   'population_trend_long': 'I',
   'population_trend_long_magnitude_min': None,
   'population_trend_long_magnitude_max': None,
   'population_trend_long_magnitude': 400,
   'population_trend_long_method': 'completeSurvey',
   'population_trend_long_sources': 'Dvorak et al. 1994',
   'population_trend_info': None,
   'sensitive_species': False,
   'distribution_period': '2013-2018',
   'distribution_map': True,
   'distribution_grid_area': '11100',
   'distribution_surface_area': 11800,
   'distribution_method': 'completeSurvey',
   'additional_distribution_map': False,
   'distribution_source': 'BirdLife Austria, unpublished data from www.ornitho.at',
   'distribution_info': None,
   'distribution_trend_period': '2007-2018',
   'distribution_trend': 'S',
   'distribution_trend_magnitude_min': None,
   'distribution_trend_magnitude_max': None,
   'distribution_trend_magnitude': 2,
   'distribution_trend_method': 'completeSurvey',
   'distribution_trend_source': 'BirdLife Austria, unpublished data from www.ornitho.at; BirdLife Austria, unpublished archive data',
   'distribution_trend_long_period': '1981-2018',
   'distribution_trend_long': 'I',
   'distribution_trend_long_magnitude_min': 20,
   'distribution_trend_long_magnitude_max': 40,
   'distribution_trend_long_magnitude': None,
   'distribution_trend_long_method': 'completeSurvey',
   'distribution_trend_long_source': 'Dvorak, Ranner & Berg 1993 (Atlas of Austrian Breeding Birds)',
   'distribution_trend_info': None,
   'plan': 'NA',
   'national_plan_adopted': False,
   'measures_taken': None,
   'effectiveness_SAPs': None,
   'effectiveness_MPs': None,
   'further_info': None,
   'spa_population_unit': 'p',
   'spa_population_min': 99,
   'spa_population_max': 207,
   'spa_population': None,
   'spa_population_estimate_type': 'estimate',
   'spa_population_method': 'estimatePartial',
   'spa_population_trend': 'I',
   'spa_population_trend_method': 'estimatePartial',
   'spa_info': None,
   'use_for_statistics': True,
   'popsize_etc': 500.0,
   'spa_popsize_etc': 153.0,
   'spa_coverage_etc': 30.6},
  {'country': 'AT',
   'season': 'B',
   'speciescode': 'A023',
   'speciesname': 'Nycticorax nycticorax',
   'sub_unit': None,
   'alternative_speciesname': None,
   'common_speciesname': 'Nachtreiher',
   'population_date': '2013-2017',
   'population_size_unit': 'p',
   'population_size_min': 53,
   'population_size_max': 85,
   'population_size': None,
   'population_estimate_type': 'estimate',
   'population_method': 'completeSurvey',
   'population_sources': 'Dvorask et al. 2016; Erwin Nemeth, unpublished data from the bird monitoring programm of the Neusiedler See - Seewinkel national park; unpublished reports of the Gebietsbetreuung Unterer Inn; BirdLife Austria, unpublished data from www.ornitho.at',
   'population_info': None,
   'population_trend_period': '2007-2017',
   'population_trend': 'I',
   'population_trend_magnitude_min': None,
   'population_trend_magnitude_max': None,
   'population_trend_magnitude': 13,
   'population_trend_method': 'completeSurvey',
   'population_trend_sources': 'BirdLife Austria, unpublished data from the bird monitoring programm of the Neusiedler See - Seewinkel national park, unpublished reports of the Gebietsbetreuung Unterer Inn, BirdLife Austria, unpublished data from www.ornitho.at, Ranner et al. 2015',
   'population_trend_long_period': '1981-2018',
   'population_trend_long': 'I',
   'population_trend_long_magnitude_min': None,
   'population_trend_long_magnitude_max': None,
   'population_trend_long_magnitude': 250,
   'population_trend_long_method': 'completeSurvey',
   'population_trend_long_sources': 'BirdLife Austria, unpublished data from the bird monitoring programm of the Neusiedler See - Seewinkel national park, unpublished reports of the Gebietsbetreuung Unterer Inn, BirdLife Austria, unpublished data from www.ornitho.at, Dvorak, Ranner & Berg  1993 (Atlas of Austrian breeding birds 1981-1985)',
   'population_trend_info': None,
   'sensitive_species': False,
   'distribution_period': '2013-2018',
   'distribution_map': True,
   'distribution_grid_area': '700',
   'distribution_surface_area': 700,
   'distribution_method': 'completeSurvey',
   'additional_distribution_map': False,
   'distribution_source': 'BirdLife Austria, unpublished data from www.ornitho.at',
   'distribution_info': None,
   'distribution_trend_period': '2007-2018',
   'distribution_trend': 'I',
   'distribution_trend_magnitude_min': 10,
   'distribution_trend_magnitude_max': 30,
   'distribution_trend_magnitude': None,
   'distribution_trend_method': 'completeSurvey',
   'distribution_trend_source': 'BirdLife Austria, unpublished data from www.ornitho.at, BirdLife Austria, unpublished archive data',
   'distribution_trend_long_period': '1981-2018',
   'distribution_trend_long': 'I',
   'distribution_trend_long_magnitude_min': None,
   'distribution_trend_long_magnitude_max': None,
   'distribution_trend_long_magnitude': 200,
   'distribution_trend_long_method': 'completeSurvey',
   'distribution_trend_long_source': 'BirdLife Austria, unpublished data from www.ornitho.at, Dvorak, Ranner & Berg  1993 (Atlas of Austrian breeding birds 1981-1985)',
   'distribution_trend_info': None,
   'plan': 'NA',
   'national_plan_adopted': False,
   'measures_taken': None,
   'effectiveness_SAPs': None,
   'effectiveness_MPs': None,
   'further_info': None,
   'spa_population_unit': 'p',
   'spa_population_min': 53,
   'spa_population_max': 85,
   'spa_population': None,
   'spa_population_estimate_type': 'estimate',
   'spa_population_method': 'completeSurvey',
   'spa_population_trend': 'I',
   'spa_population_trend_method': 'completeSurvey',
   'spa_info': None,

In [11]:
eea_eunis_countries_df=pd.DataFrame(jsonres['results'])

In [12]:
eea_eunis_countries_df

,country,season,speciescode,speciesname,sub_unit,alternative_speciesname,common_speciesname,population_date,population_size_unit,population_size_min,...,spa_population,spa_population_estimate_type,spa_population_method,spa_population_trend,spa_population_trend_method,spa_info,use_for_statistics,popsize_etc,spa_popsize_etc,spa_coverage_etc
0,AT,B,A004,Tachybaptus ruficollis,None,None,Zwergtaucher,2013-2018,p,900.0,...,NaN,None,None,None,None,None,True,1050.0,NaN,NaN
1,AT,B,A005,Podiceps cristatus,None,None,Haubentaucher,2013-2018,p,1000.0,...,NaN,None,None,None,None,None,True,1350.0,NaN,NaN
2,AT,B,A008,Podiceps nigricollis,None,None,Schwarzhalstaucher,2013-2017,p,0.0,...,NaN,estimate,completeSurvey,D,completeSurvey,None,True,10.5,10.5,100.00000
3,AT,B,A021,Botaurus stellaris,None,None,Rohrdommel,2013-2018,cmales,110.0,...,NaN,estimate,completeSurvey,D,completeSurvey,None,True,140.0,140.0,100.00000
4,AT,B,A022,Ixobrychus minutus,None,None,Zwergdommel,2013-2018,p,400.0,...,NaN,estimate,estimatePartial,I,estimatePartial,None,True,500.0,153.0,30.60000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8300,UK,W,A857,Spatula clypeata,None,None,Northern Shoveler,2012-2016,i,NaN,...,4761.0,estimate,completeSurvey,I,completeSurvey,http://jncc.defra.gov.uk/pdf/UKSPA3_Shoveler A...,True,19398.0,4761.0,24.54377
8301,UK,W,A861,Calidris pugnax,None,None,Ruff,2012-2016,i,NaN,...,242.0,estimate,completeSurvey,D,completeSurvey,http://jncc.defra.gov.uk/pdf/UKSPA3_Ruff Philo...,True,920.0,242.0,26.30435
8302,UK,W,A862,Hydrocoloeus minutus,None,None,Little Gull,2013-2018,None,NaN,...,NaN,None,None,None,None,None,True,NaN,NaN,NaN
8303,UK,W,A889,Mareca strepera,None,None,Gadwall,2012-2016,i,NaN,...,4785.0,estimate,completeSurvey,I,completeSurvey,http://jncc.defra.gov.uk/pdf/UKSPA3_GadwallAna...,True,31217.0,4785.0,15.32819
8304,UK,W,A900,Melanitta nigra s. str.,sensu stricto [excluding americana],None,Common Scoter,2012-2016,i,NaN,...,132135.0,estimate,completeSurvey,I,completeSurvey,http://jncc.defra.gov.uk/pdf/UKSPA3_CommonScot...,True,133615.0,132135.0,98.89234

Now of course, you can try to understand what each of these fields really is (check the metadata table!)

For example, it may be intereting to relate this with disaster data (https://public.emdat.be/data) throughout the years...